#!/bin/bash
# ============================================================
# MoA Railway Unified Startup Script
#
# Starts BOTH services in a single Railway container:
#   1. OpenClaw Gateway (background) — agent with heartbeat, cron, memory, tools, skills
#   2. MoA Webhook Server (foreground) — KakaoTalk, Telegram, Discord, Slack, WhatsApp, LINE
#
# The MoA server connects to the local OpenClaw gateway for enhanced AI.
# If the gateway fails to start, MoA still works with direct LLM calls.
#
# Environment variables:
#   OPENCLAW_GATEWAY_ENABLED — "true" (default) or "false" to skip gateway
#   OPENCLAW_STATE_DIR       — Data directory (default: /data/.openclaw)
#   PORT                     — MoA server port (default: 8788, Railway overrides)
# ============================================================

set -e

echo "================================================================"
echo "[MoA] Railway Unified Startup — Master of AI + OpenClaw Agent"
echo "================================================================"

# ── Persistent data directory (Railway Volume at /data) ──
DATA_DIR="${OPENCLAW_STATE_DIR:-/data/.openclaw}"
mkdir -p "$DATA_DIR" 2>/dev/null || true

# Set HOME so OpenClaw reads config from the volume
export OPENCLAW_STATE_DIR="$DATA_DIR"

GATEWAY_PORT=18789
GATEWAY_BIND="127.0.0.1"
GATEWAY_ENABLED="${OPENCLAW_GATEWAY_ENABLED:-true}"
GATEWAY_PID=""

# ── Create minimal OpenClaw config if not exists ──
setup_openclaw_config() {
  CONFIG_DIR="$DATA_DIR"
  mkdir -p "$CONFIG_DIR" 2>/dev/null || true
  CONFIG_FILE="$CONFIG_DIR/config.yaml"

  if [ -f "$CONFIG_FILE" ]; then
    echo "[MoA] OpenClaw config exists at $CONFIG_FILE"
    return
  fi

  cat > "$CONFIG_FILE" << 'YAML'
# Auto-generated by MoA Railway startup
# This enables OpenClaw agent features (heartbeat, cron, memory, tools)
# Modify as needed — changes persist across Railway deploys (volume)

gateway:
  mode: local

agents:
  defaults:
    heartbeat:
      enabled: true
      every: "30m"
YAML
  echo "[MoA] Created OpenClaw config at $CONFIG_FILE"
}

# ── Start OpenClaw Gateway ──
start_openclaw_gateway() {
  if [ "$GATEWAY_ENABLED" != "true" ]; then
    echo "[MoA] OpenClaw gateway: DISABLED (set OPENCLAW_GATEWAY_ENABLED=true to enable)"
    return
  fi

  if [ ! -f dist/entry.js ]; then
    echo "[MoA] OpenClaw gateway: SKIPPED (dist/entry.js not found — run pnpm build first)"
    return
  fi

  setup_openclaw_config

  echo "[MoA] Starting OpenClaw gateway on $GATEWAY_BIND:$GATEWAY_PORT..."
  HOME="$DATA_DIR" node dist/entry.js gateway run \
    --port "$GATEWAY_PORT" \
    --bind "$GATEWAY_BIND" \
    --force \
    2>&1 | while IFS= read -r line; do echo "[OpenClaw] $line"; done &
  GATEWAY_PID=$!
  echo "[MoA] OpenClaw gateway PID: $GATEWAY_PID"

  # Wait for gateway to be healthy (max 30 seconds)
  echo -n "[MoA] Waiting for gateway health"
  for i in $(seq 1 30); do
    if wget -qO- "http://$GATEWAY_BIND:$GATEWAY_PORT/health" > /dev/null 2>&1; then
      echo " OK"
      echo "[MoA] OpenClaw gateway: HEALTHY"
      export MOA_OPENCLAW_GATEWAY_URL="http://$GATEWAY_BIND:$GATEWAY_PORT"
      return
    fi
    # Check if process died
    if ! kill -0 "$GATEWAY_PID" 2>/dev/null; then
      echo " FAILED"
      echo "[MoA] OpenClaw gateway: process exited — continuing without it"
      GATEWAY_PID=""
      return
    fi
    echo -n "."
    sleep 1
  done

  echo " TIMEOUT"
  echo "[MoA] OpenClaw gateway: did not become healthy in 30s — continuing without it"
}

# ── Graceful shutdown ──
cleanup() {
  echo "[MoA] Shutting down..."
  if [ -n "$GATEWAY_PID" ] && kill -0 "$GATEWAY_PID" 2>/dev/null; then
    echo "[MoA] Stopping OpenClaw gateway (PID: $GATEWAY_PID)..."
    kill "$GATEWAY_PID" 2>/dev/null || true
    wait "$GATEWAY_PID" 2>/dev/null || true
  fi
  exit 0
}
trap cleanup SIGTERM SIGINT

# ── Main ──
start_openclaw_gateway

echo ""
echo "[MoA] Starting MoA webhook server on port ${PORT:-8788}..."
echo "================================================================"

# Start MoA server (foreground) — this is the Railway-facing process
exec ./node_modules/.bin/tsx extensions/kakao/server.ts
